# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Randocity
email: dawson.ted@gmail.com
description: This is a site about randomness. It is random.
baseurl: "/randomsite" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site
twitter_username:
github_username: tedawson

# Build settings
markdown: kramdown
